#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

LDAP_PASS=turnkey
LDAP_DOMAIN=example.com
INITHOOKS=/usr/lib/inithooks

# change shared folder options to allow anyone in group to write any files
CONF=/etc/samba/smb.conf
sed -i "s|path = /srv/storage|path = /srv/storage\n    force group = users\n    force create mode = 0060\n    force directory mode = 0060|" $CONF
