#!/bin/bash -ex
install()
{
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -y \
        -o DPkg::Options::=--force-confdef \
        -o DPkg::Options::=--force-confold \
        install $@
}

STORAGE=/srv/storage

if [ -d "${STORAGE}/data" ]; then
  STORAGE=${STORAGE}/data
fi

# remove sticky bit from storage directory
chmod -t $STORAGE

# remove the null password option
CONF=/etc/samba/smb.conf
sed -i "/null passwords/d" $CONF

# change shared folder options to allow anyone in group to write any files
sed -i "s|[storage]|[storage]\n    force group = users\n    force create mode = 0060\n    force directory mode = 0060|" $CONF

